name: Build cadical binaries

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - src/**
      - .github/workflows/build.yaml
jobs:
  build_linux_binary:
    name: Build Linux binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: ./configure -fPIC && make

      - name: List files
        run: ls -la build
